### ISSUE TITLE
Compared to facebookgo/inject

### ISSUE THREAD

**Issue by cep21** [karlkfi/inject#2]
Hi,

I'm looking at this and https://github.com/facebookgo/inject.  Are you familiar with this injection alternative?  I was wondering if you could compare quickly what you think the best advantages/disadvantages and philosophies of the two frameworks are.

**Comment by karlkfi** [comment]
Facebook's library is a good alternative. It's based on a more declarative dependency definition similar to Spring, using named keys. 

I specifically designed mine to optimize for different qualities:
- runtime dependency definition
- compile time type checking
- minimize type casting by the user
- ordered dependency chain resolution 
- introspective graph debugging at runtime
- optional multi-stage graph definition
