### ISSUE TITLE
Inject and mocks

### ISSUE THREAD

**Issue by arvenil** [karlkfi/inject#5]
Hi,

Let's start with praise, I really love your DI design :), not based on tags, using constructors, allows to use private structs - great!.
I was hoping to use it in a project for managing my real deps and mocks, however I have some doubts how could I use it to solve my issue.

Right now my main looks like this (of course it really has +20+ more deps;)):

``` go
serviceA := pkgA.New()
serviceB := pkbB.New(serviceA)
serviceB.DoStuff()
```

Now, what I would like to achieve is to replace real instances with the mocks in my tests, but defining all the deps, in every test pretty quickly gets really annoying as I already have 20+ services. So I was thinking about creating dependency graph and then using mocks instead of real objects.

``` go
    graph := inject.NewGraph()

    var (
        serviceA pkgA.InterfaceA
        serviceB pkgB.InterfaceB
    )

    graph.Define(&serviceA, inject.NewProvider(pkgA.New))
    graph.Define(&serviceB, inject.NewProvider(pkgB.New, &serviceA))

    graph.Resolve(&serviceA)
    serviceA.DoStuff() 
```

Great, this looks cool!... but doesn't solve anything as how can I replace real objects with mocks?

I had three ideas

1.
Assign a mock to `serviceB` var after deps being resolved

``` go
    graph := inject.NewGraph()

    var (
        serviceA pkgA.InterfaceA
        serviceB pkgB.InterfaceB
    )

    graph.Define(&serviceA, inject.NewProvider(pkgA.New))
    graph.Define(&serviceB, inject.NewProvider(pkgB.New, &serviceA))

    graph.Resolve(&serviceA)
    serviceB = &pkgMockB.New()

    serviceA.DoStuff() 
```

but this can't work as we replace pointer... i tried to replace value but since this is an interface it seems to be impossible to replace in a interface one type (real struct) with another type (mock struct).
http://stackoverflow.com/a/29545033/916440
Before I continue with my second idea, I still think graph could allow replacing object (maybe extend api?) after graph.Resolve()

2.
Second idea was to do the same but before Resolve(). So I was thinking that maybe library checks if `serviceB` is `nil` and only then it creates new instance. But it doesn't do that.

``` go
    graph := inject.NewGraph()

    var (
        serviceA pkgA.InterfaceA
        serviceB pkgB.InterfaceB
    )

    serviceB = &pkgMockB.New() // already created so graph could skip creating new instance
    graph.Define(&serviceA, inject.NewProvider(pkgA.New))
    graph.Define(&serviceB, inject.NewProvider(pkgB.New, &serviceA))

    graph.Resolve(&serviceA)

    serviceA.DoStuff() 
```

3.
Last idea is the most obvious one - I mean, it must work :) however it's less efficient/flexible.
Simply to put I need to add code that provides different set of providers for tests and different set of providers for main.

``` go
func buildGrap(providerServiceA, providerServiceB *graph.Provider) *graph.Graph {
    graph := inject.NewGraph()

    var (
        serviceA pkgA.InterfaceA
        serviceB pkgB.InterfaceB
    )

    graph.Define(&serviceA, providerServiceA)
    graph.Define(&serviceB, providerServiceB)

    graph.Resolve(&serviceA)

    return graph
}
```

This should work. The only issue is that every time I create test I will need to provide all providers. Probably adding something like registry for providers could be a good idea. With registry I could create all the mocks by default and then allow in tests to replace the ones that I want.

Any thoughts about this? How you would solve the issue with real code vs using mocks in tests and avoiding the need of recreating mocks in every single test?

**Comment by karlkfi** [comment]
Option 3 is what I had in mind, but I understand the desire to be more DRY. 

The graph isn't really designed to be mutable other than adding. Sounds like you want a graph.Redefine method or something. You'd still need to have the pointer key tho in order to update the value in the graph. And you'd have to do it before graph.Resolve. 

Would you like to make a PR to add that?

**Comment by karlkfi** [comment]
Correction: if you just do another graph.Define with the same pointer key before graph.Resolve it will replace the old definition. 

So all you need to do for tests is abstract the graph definitions and let the test update the graph before resolving.
